Add more context for admin stacks
spacelift-io/user-documentation pull request #136
Opened 2023-01-30 14:34 UTC by jubranNassar

# Description of the change

I added an info box in the admin section of the stack settings page to provide more clarity for admin stacks.

## Checklist

Please make sure that the proposed change checks all the boxes below before requesting a review:

- [ ] I have reviewed the [guidelines for contributing](https://github.com/spacelift-io/user-documentation/blob/main/CONTRIBUTING.md) to this repository.
- [ ] The preview looks fine.
- [ ] The tests pass.
- [ ] The commit history is clean and meaningful.
- [ ] The pull request is opened against the `main` branch.
- [ ] The pull request is no longer marked as a draft.
- [ ] You agree to license your contribution under the [MIT license](https://github.com/spacelift-io/user-documentation/blob/main/LICENSE) to Spacelift.

If the proposed change is ready to be merged, please request a review from `@spacelift-io/solutions-engineering`. Someone will review and merge the pull request.

Thank you for your contribution! 🙇

2023-01-30 14:42 UTC, jmfontaine commented on docs/concepts/stack/stack-settings.md
> +!!! info
[The first sentence](https://github.com/spacelift-io/user-documentation/pull/136/files#diff-a10a10f63b2797918f4e6756fcf86764fb175ad6c6d8d2ef94513cc2cbcf3986L13) basically says that.

Should you not update that sentence instead?

> This setting indicates whether a stack has administrative privileges for the [Space](../spaces/README.md) it is in.

2023-01-30 14:47 UTC, jubranNassar commented on docs/concepts/stack/stack-settings.md
> +!!! info
update the first sentence instead of the info box?

2023-01-30 20:52 UTC, jmfontaine requested changes

2023-01-30 20:52 UTC, jmfontaine commented on docs/concepts/spaces/README.md
> +Initially, you start with a `root` and a `legacy` space. The `root` space is the top-level space of your account, while the `legacy` space exists for backward compatibility with pre-spaces RBAC. [You
Please link to the documentation, not the preview.

2023-01-30 20:52 UTC, jmfontaine commented on docs/concepts/stack/stack-settings.md
> +This setting indicates whether a stack has administrative privileges within the [space](https://spacelift-user-documentation-pr-136.onrender.com/concepts/spaces/index.html) it lives in. Runs executed
Please link to the documentation, not the preview.

2023-01-30 21:55 UTC, jubranNassar commented on docs/concepts/spaces/README.md
> +Initially, you start with a `root` and a `legacy` space. The `root` space is the top-level space of your account, while the `legacy` space exists for backward compatibility with pre-spaces RBAC. [You
done

2023-02-01 14:11 UTC, jmfontaine requested changes

2023-02-01 19:34 UTC, jubranNassar commented on docs/concepts/spaces/README.md
> +Initially, you start with a `root` and a `legacy` space. The `root` space is the top-level space of your account, while the `legacy` space exists for backward compatibility with pre-spaces RBAC. [You
ahh yes, I just fixed it with next commit

2023-02-02 14:12 UTC, jmfontaine approved these changes

2023-02-02 15:52 UTC, merged