updates to reflect enterprise features
spacelift-io/user-documentation pull request #286
Opened 2023-07-13 09:31 UTC by Daniellem97

# Description of the change

## Checklist

Please make sure that the proposed change checks all the boxes below before requesting a review:

- [x] I have reviewed the [guidelines for contributing](https://github.com/spacelift-io/user-documentation/blob/main/CONTRIBUTING.md) to this repository.
- [x] The preview looks fine.
- [x] The tests pass.
- [x] The commit history is clean and meaningful.
- [x] The pull request is opened against the `main` branch.
- [x] The pull request is no longer marked as a draft.
- [x] You agree to license your contribution under the [MIT license](https://github.com/spacelift-io/user-documentation/blob/main/LICENSE) to Spacelift (not required for Spacelift employees).
- [x] You have updated the navigation files correctly:
    - [ ] No new pages have been added, or;
    - [ ] Only _nav.yaml_ has been updated because the changes only apply to SaaS, or;
    - [ ] Only _nav.self-hosted.yaml_ has been updated because the changes only apply to Self-Hosted, or;
    - [ ] Both _nav.yaml_ and _nav.self-hosted.yaml_ have been updated.

If the proposed change is ready to be merged, please request a review from `@spacelift-io/solutions-engineering`. Someone will review and merge the pull request.

_Spacelift employees should request reviews from the relevant engineers and are allowed to merge pull requests after they got at least one approval._

Thank you for your contribution! 🙇

2023-07-18 22:03 UTC, jmfontaine requested changes
I could identify at least two more features that are Enterprise plan only:

- Advanced Scheduling
- Private Source Control System

2023-07-18 22:03 UTC, jmfontaine commented on docs/concepts/stack/drift-detection.md
> +    Note that, at least currently, drift detection only works on private workers.
I would remove "at least currently." I do not want to even look like we are committing to changing that any time soon.

2023-07-18 22:03 UTC, jmfontaine commented on docs/integrations/single-sign-on/aws-iam-identity-saml-setup-guide.md
> +    Note that, at least currently, SSO Integration with SAML 2.0 is an enterprise feature.
I would remove "at least currently". I do not want to even look like we are committing to changing that any time soon.

2023-07-18 22:03 UTC, jmfontaine commented on docs/integrations/audit-trail.md
> +    Note that, the audit trail is an enterprise feature.
You are the English-native speaker but is the comma necessary here?

2023-07-20 14:18 UTC, Daniellem97 commented
Changes made

2023-07-20 14:20 UTC, jmfontaine reviewed
Does saying "Enterprise plan" sounds better than "Enterprise"?

2023-07-20 14:20 UTC, jmfontaine commented on docs/integrations/single-sign-on/aws-iam-identity-saml-setup-guide.md
> +    Note that SSO Integration with SAML 2.0 is an enterprise feature.
```suggestion
    Note that SSO Integration with SAML 2.0 is an Enterprise plan feature.
```

2023-07-20 14:28 UTC, Daniellem97 commented
Agreed, committed changes

2023-07-20 14:58 UTC, jmfontaine approved these changes

2023-07-20 15:02 UTC, merged