Added reference to Magidoc
spacelift-io/user-documentation pull request #290
Opened 2023-07-21 22:39 UTC by jacobjSL

# Description of the change

Added a reference to Magidoc, a tool that can help with static api documentation. 
## Checklist

Please make sure that the proposed change checks all the boxes below before requesting a review:

- [ ] I have reviewed the [guidelines for contributing](https://github.com/spacelift-io/user-documentation/blob/main/CONTRIBUTING.md) to this repository.
- [ ] The preview looks fine.
- [ ] The tests pass.
- [ ] The commit history is clean and meaningful.
- [ ] The pull request is opened against the `main` branch.
- [ ] The pull request is no longer marked as a draft.
- [ ] You agree to license your contribution under the [MIT license](https://github.com/spacelift-io/user-documentation/blob/main/LICENSE) to Spacelift (not required for Spacelift employees).
- [ ] You have updated the navigation files correctly:
    - [ ] No new pages have been added, or;
    - [ ] Only _nav.yaml_ has been updated because the changes only apply to SaaS, or;
    - [ ] Only _nav.self-hosted.yaml_ has been updated because the changes only apply to Self-Hosted, or;
    - [ ] Both _nav.yaml_ and _nav.self-hosted.yaml_ have been updated.

If the proposed change is ready to be merged, please request a review from `@spacelift-io/solutions-engineering`. Someone will review and merge the pull request.

_Spacelift employees should request reviews from the relevant engineers and are allowed to merge pull requests after they got at least one approval._

Thank you for your contribution! 🙇

2023-07-21 22:43 UTC, jmfontaine requested changes

2023-07-21 22:43 UTC, jmfontaine commented on docs/integrations/api.md
> +Our GraphQL schema is self-documenting. The best way to view the latest documentation is using a dedicated GraphQL client like [Insomnia](https://insomnia.rest/){: rel="nofollow"} or [GraphiQL](https
External links must be marked as `nofollow` for SEO reasons.

```suggestion
Our GraphQL schema is self-documenting. The best way to view the latest documentation is using a dedicated GraphQL client like [Insomnia](https://insomnia.rest/){: rel="nofollow"} or [GraphiQL](https://github.com/skevy/graphiql-app){: rel="nofollow"}. You may also view the documentation using a static documentation website generator like [Magidoc](https://magidoc.js.org/introduction/quickstart){: rel="nofollow"}. _Note: As of the writing of these examples, the latest version of Postman does not currently support viewing GraphQL Schemas from a URL, but does support autocompletion._
```

2023-07-21 22:43 UTC, jmfontaine commented on docs/integrations/api.md
> +![](../assets/screenshots/magidoc-stack.png)
Could you either add context or remove this section? I would lean toward the latter since users can go to Magidoc website to get instructions. There is no point in duplicating them here unless there are caveats they need to be aware of

2023-07-21 22:57 UTC, jacobjSL commented on docs/integrations/api.md
> +![](../assets/screenshots/magidoc-stack.png)
I can remove, that makes sense.

2023-07-21 22:58 UTC, jacobjSL commented on docs/integrations/api.md
> +Our GraphQL schema is self-documenting. The best way to view the latest documentation is using a dedicated GraphQL client like [Insomnia](https://insomnia.rest/){: rel="nofollow"} or [GraphiQL](https
Was not aware of that, thanks for the tip!

2023-07-21 23:06 UTC, jacobjSL commented
@jmfontaine Updated based off your suggestions.

2023-07-23 17:07 UTC, jmfontaine approved these changes

2023-07-24 23:57 UTC, merged