Updated VCS Agent documentation to mention Docker and Helm installations
spacelift-io/user-documentation pull request #317
Opened 2023-08-24 12:07 UTC by eminalemdar

# Description of the change

I've added additional information about Docker and Helm installations for VCS Agent.

## Checklist

Please make sure that the proposed change checks all the boxes below before requesting a review:

- [ ] I have reviewed the [guidelines for contributing](https://github.com/spacelift-io/user-documentation/blob/main/CONTRIBUTING.md) to this repository.
- [ ] The preview looks fine.
- [ ] The tests pass.
- [ ] The commit history is clean and meaningful.
- [ ] The pull request is opened against the `main` branch.
- [ ] The pull request is no longer marked as a draft.
- [ ] You agree to license your contribution under the [MIT license](https://github.com/spacelift-io/user-documentation/blob/main/LICENSE) to Spacelift (not required for Spacelift employees).
- You have updated the navigation files correctly:
    - [ ] No new pages have been added, or;
    - [ ] Only _nav.yaml_ has been updated because the changes only apply to SaaS, or;
    - [ ] Only _nav.self-hosted.yaml_ has been updated because the changes only apply to Self-Hosted, or;
    - [ ] Both _nav.yaml_ and _nav.self-hosted.yaml_ have been updated.

If the proposed change is ready to be merged, please request a review from `@spacelift-io/solutions-engineering`. Someone will review and merge the pull request.

_Spacelift employees should request reviews from the relevant engineers and are allowed to merge pull requests after they got at least one approval._

Thank you for your contribution! 🙇

2023-08-26 14:45 UTC, jmfontaine requested changes

2023-08-26 14:45 UTC, jmfontaine commented on docs/concepts/vcs-agent-pools.md
> +  -e "SPACELIFT_VCS_AGENT_VENDOR=<bitbucket_datacenter>" \
The placeholder values format should be consistent and match the style used in the rest of the documentation.

2023-08-26 14:45 UTC, jmfontaine commented on docs/concepts/vcs-agent-pools.md
> +You can run the VCS Agent as a container using our image. You can use this command to run the VCS Agent via Docker:
This can be simplified into: "You can run the VCS Agent as a Docker container:" (followed by the command).

2023-08-26 20:31 UTC, eminalemdar commented on docs/concepts/vcs-agent-pools.md
> +You can run the VCS Agent as a container using our image. You can use this command to run the VCS Agent via Docker:
Done

2023-08-26 20:32 UTC, eminalemdar commented on docs/concepts/vcs-agent-pools.md
> +  -e "SPACELIFT_VCS_AGENT_VENDOR=<bitbucket_datacenter>" \
Done

2023-08-29 12:52 UTC, eminalemdar commented
> Looks good minus a tiny nit. And like I mentioned on Slack, I think it might be worth linking to the Git repo containing the Helm chart.

I think we can add the link to the Git repo after changing the name of the repo, with a new PR or we can wait to merge this PR until those are updated. WDYT @adamconnelly?

2023-08-29 15:01 UTC, jmfontaine requested changes

2023-08-29 15:01 UTC, jmfontaine commented on docs/concepts/vcs-agent-pools.md
> +  -e "SPACELIFT_VCS_AGENT_VENDOR=<bitbucket_datacenter>" \
I agree with @adamconnelly and this applies to this value as well.

2023-08-29 15:06 UTC, eminalemdar commented on docs/concepts/vcs-agent-pools.md
> +  -e "SPACELIFT_VCS_AGENT_VENDOR=<bitbucket_datacenter>" \
do you mean the screenshots or something else? because both the base endpoint and the vendor are for bitbucket datacenter configuration in this example after my commit

2023-08-29 15:08 UTC, jmfontaine commented on docs/concepts/vcs-agent-pools.md
> +  -e "SPACELIFT_VCS_AGENT_VENDOR=<bitbucket_datacenter>" \
I was referring to this placeholder: `SPACELIFT_VCS_AGENT_POOL_TOKEN=<VCS Token>`.

I suggested a fix to make it consistent with the other placeholders.

2023-08-29 16:27 UTC, adamconnelly commented
> 

I don't mind either way @eminalemdar. Just whatever makes the most sense to you.

2023-08-31 11:58 UTC, eminalemdar commented on docs/concepts/vcs-agent-pools.md
> +  -e "SPACELIFT_VCS_AGENT_VENDOR=<bitbucket_datacenter>" \
done

2023-08-31 11:58 UTC, eminalemdar commented on docs/concepts/vcs-agent-pools.md
> +  -e "SPACELIFT_VCS_AGENT_TARGET_BASE_ENDPOINT=<http://169.254.0.10:7990>" \
done

2023-08-31 11:58 UTC, eminalemdar commented on docs/concepts/vcs-agent-pools.md
> +  -e "SPACELIFT_VCS_AGENT_VENDOR=<bitbucket_datacenter>" \
done

2023-08-31 13:14 UTC, jmfontaine approved these changes

2023-08-31 13:15 UTC, merged