Added a section to describe Terraform State import
spacelift-io/user-documentation pull request #332
Opened 2023-09-07 11:46 UTC by eminalemdar

# Description of the change

I've added an additional section to the State Management documentation for Terraform to describe importing existing Terraform State files into Spacelift in Stack creation process.

## Checklist

Please make sure that the proposed change checks all the boxes below before requesting a review:

- [ ] I have reviewed the [guidelines for contributing](https://github.com/spacelift-io/user-documentation/blob/main/CONTRIBUTING.md) to this repository.
- [ ] The preview looks fine.
- [ ] The tests pass.
- [ ] The commit history is clean and meaningful.
- [ ] The pull request is opened against the `main` branch.
- [ ] The pull request is no longer marked as a draft.
- [ ] You agree to license your contribution under the [MIT license](https://github.com/spacelift-io/user-documentation/blob/main/LICENSE) to Spacelift (not required for Spacelift employees).
- You have updated the navigation files correctly:
    - [ ] No new pages have been added, or;
    - [ ] Only _nav.yaml_ has been updated because the changes only apply to SaaS, or;
    - [ ] Only _nav.self-hosted.yaml_ has been updated because the changes only apply to Self-Hosted, or;
    - [ ] Both _nav.yaml_ and _nav.self-hosted.yaml_ have been updated.

If the proposed change is ready to be merged, please request a review from `@spacelift-io/solutions-engineering`. Someone will review and merge the pull request.

_Spacelift employees should request reviews from the relevant engineers and are allowed to merge pull requests after they got at least one approval._

Thank you for your contribution! 🙇

2023-09-07 21:41 UTC, jmfontaine approved these changes

2023-09-07 21:41 UTC, jmfontaine commented on docs/vendors/terraform/state-management.md
> +If you are managing your infrastructure resources with Terraform prior to start using Spacelift, you would probably have an existing Terraform State file that you manage yourself. You have the option
What about the following?

```suggestion
When creating a stack, you can optionally import an existing Terraform state file so that Spacelift can manage it going forward.
```

2023-09-07 21:41 UTC, jmfontaine commented on docs/vendors/terraform/state-management.md
> +You can import your existing Terraform State files in Stack creation process.
This can be removed if the suggestion above is accepted.

```suggestion
```

2023-09-07 21:41 UTC, jmfontaine commented on docs/vendors/terraform/state-management.md
> +![](../../assets/screenshots/Stack_settings_importing_state_file.png)
The screenshot uses chalk orange lines, while the other screenshots use solid red lines. Please make this screenshot consistent with the rest of the documentation.

More generally, we want to approach editing this documentation like changing legacy source code: try to make your changes blend in nicely.

2023-09-07 21:42 UTC, jmfontaine requested changes
I mistakenly approved. 🤦‍♂️

2023-09-08 07:34 UTC, eminalemdar commented on docs/vendors/terraform/state-management.md
> +![](../../assets/screenshots/Stack_settings_importing_state_file.png)
Done

2023-09-11 18:47 UTC, jmfontaine approved these changes

2023-09-12 07:48 UTC, merged