adding no follow
spacelift-io/user-documentation pull request #367
Opened 2023-10-16 20:00 UTC by Daniellem97

# Description of the change

## Checklist

Please make sure that the proposed change checks all the boxes below before requesting a review:

- [ ] I have reviewed the [guidelines for contributing](https://github.com/spacelift-io/user-documentation/blob/main/CONTRIBUTING.md) to this repository.
- [ ] The preview looks fine.
- [ ] The tests pass.
- [ ] The commit history is clean and meaningful.
- [ ] The pull request is opened against the `main` branch.
- [ ] The pull request is no longer marked as a draft.
- [ ] You agree to license your contribution under the [MIT license](https://github.com/spacelift-io/user-documentation/blob/main/LICENSE) to Spacelift (not required for Spacelift employees).
- You have updated the navigation files correctly:
    - [ ] No new pages have been added, or;
    - [ ] Only _nav.yaml_ has been updated because the changes only apply to SaaS, or;
    - [ ] Only _nav.self-hosted.yaml_ has been updated because the changes only apply to Self-Hosted, or;
    - [ ] Both _nav.yaml_ and _nav.self-hosted.yaml_ have been updated.

If the proposed change is ready to be merged, please request a review from `@spacelift-io/solutions-engineering`. Someone will review and merge the pull request.

_Spacelift employees should request reviews from the relevant engineers and are allowed to merge pull requests after they got at least one approval._

Thank you for your contribution! 🙇

2023-10-18 10:56 UTC, eminalemdar requested changes

2023-10-18 10:56 UTC, eminalemdar commented on docs/concepts/spacectl.md
> +Install [`spacectl-bin`](https://aur.archlinux.org/packages/spacectl-bin): from the Arch User Repository ([AUR](https://aur.archlinux.org/)):
missing the nofollow argument here

2023-10-18 10:56 UTC, eminalemdar commented on docs/integrations/cloud-providers/azure.md
> +The output includes credentials that you must protect. Be sure that you do not include these credentials in your code or check the credentials into your source control. For more information, see [Cre
why was this removed here?

2023-10-20 14:50 UTC, Daniellem97 commented on docs/integrations/cloud-providers/azure.md
> +The output includes credentials that you must protect. Be sure that you do not include these credentials in your code or check the credentials into your source control. For more information, see [Cre
removed as it is within a script

2023-10-20 14:53 UTC, eminalemdar requested changes

2023-10-20 14:53 UTC, eminalemdar commented on docs/concepts/spacectl.md
> +Install [`spacectl-bin`](https://aur.archlinux.org/packages/spacectl-bin): from the Arch User Repository ([AUR](https://aur.archlinux.org/){: rel="nofollow"}):
I think we should also have the `rel="nofollow"` for the first link too

2023-10-20 15:04 UTC, eminalemdar approved these changes

2023-10-20 15:05 UTC, merged