Pull request notifications
spacelift-io/user-documentation pull request #420
Opened 2023-12-15 15:58 UTC by mbialon

# Description of the change

## Checklist

Please make sure that the proposed change checks all the boxes below before requesting a review:

- [ ] I have reviewed the [guidelines for contributing](https://github.com/spacelift-io/user-documentation/blob/main/CONTRIBUTING.md) to this repository.
- [ ] The preview looks fine.
- [ ] The tests pass.
- [ ] The commit history is clean and meaningful.
- [ ] The pull request is opened against the `main` branch.
- [ ] The pull request is no longer marked as a draft.
- [ ] You agree to license your contribution under the [MIT license](https://github.com/spacelift-io/user-documentation/blob/main/LICENSE) to Spacelift (not required for Spacelift employees).
- You have updated the navigation files correctly:
    - [ ] No new pages have been added, or;
    - [ ] Only _nav.yaml_ has been updated because the changes only apply to SaaS, or;
    - [ ] Only _nav.self-hosted.yaml_ has been updated because the changes only apply to Self-Hosted, or;
    - [ ] Both _nav.yaml_ and _nav.self-hosted.yaml_ have been updated.

If the proposed change is ready to be merged, please request a review from `@spacelift-io/solutions-engineering`. Someone will review and merge the pull request.

_Spacelift employees should request reviews from the relevant engineers and are allowed to merge pull requests after they got at least one approval._

Thank you for your contribution! 🙇

2023-12-15 16:07 UTC, peterdeme commented on docs/concepts/policy/notification-policy.md
> +pull_request[{"id": run.commit.pull_request_id}] {
I think it'd be great to specify in what cases `pull_request_id` will exist because I was never able to make it happen with any sort of pus policy 😅

2023-12-15 16:08 UTC, peterdeme commented on docs/concepts/policy/notification-policy.md
> +  "commit": "11e344a8558c3b0ff7048acb88c60ae0a3cc2caf",
```suggestion
  "commit": input.run_updated.run.commit.hash,
```

2023-12-15 16:09 UTC, peterdeme commented on docs/concepts/policy/notification-policy.md
> +pull_request[{"id": run.commit.pull_request_id}] {
also, I'm pretty sure it's:
```suggestion
pull_request[{"id": input.run_updated.run.commit.pull_request_id}] {
```

2023-12-15 16:10 UTC, peterdeme commented on docs/concepts/policy/notification-policy.md
> +  "body": sprintf("https://example.app.spacelift.io/stack/%s/run/%s has finished", [stack.id, run.id]),
```suggestion
  "body": sprintf("https://%s.app.spacelift.io/stack/%s/run/%s has finished", [input.account.name, stack.id, run.id]),
```

2023-12-15 16:14 UTC, peterdeme commented on docs/concepts/policy/notification-policy.md
> +
```suggestion

!!! hint
    Please note that `branch` is the base branch of the pull request. For example, if it's `"branch": input.run_updated.stack.branch`, that'd mean that the policy would comment into every pull request that targets the tracked branch of the stack.

```

2023-12-15 16:20 UTC, peterdeme commented on docs/concepts/policy/notification-policy.md
> +  "commit": "11e344a8558c3b0ff7048acb88c60ae0a3cc2caf",
I'll add my notification policy that I worked on in another PR once this is merged 🖖

2023-12-21 11:18 UTC, mbialon commented on docs/concepts/policy/notification-policy.md
> +pull_request[{"id": run.commit.pull_request_id}] {
Would the hint below be useful?

2023-12-21 13:01 UTC, peterdeme approved these changes

2024-01-08 11:51 UTC, tomasmik submitted a review, later dismissed

2024-01-08 22:09 UTC, Daniellem97 requested changes
Our policy example repo now has a regal check, so perhaps we should update this example to also be in line with Regal, since it will need to be changed to this to add to the repo anyway

package spacelift

import future.keywords.contains
import future.keywords.if

pull_request contains {
	"branch": "main",
	"body": sprintf("https://%s.app.spacelift.io/stack/%s/run/%s has finished", [input.account.name, stack.id, run.id]),
} if {
	stack := input.run_updated.stack
	run := input.run_updated.run
	run.state == "FINISHED"
}

2024-01-09 11:03 UTC, peterdeme approved these changes

2024-01-09 11:06 UTC, Daniellem97 approved these changes

2024-01-09 12:04 UTC, peterdeme approved these changes

2024-01-10 10:03 UTC, merged