Update aws.md add link on how to enable sts
spacelift-io/user-documentation pull request #634
Opened 2024-09-19 21:33 UTC by akmal-spacelift

# Description of the change

## Checklist

Please make sure that the proposed change checks all the boxes below before requesting a review:

- [ ] I have reviewed the [guidelines for contributing](https://github.com/spacelift-io/user-documentation/blob/main/CONTRIBUTING.md) to this repository.
- [ ] The preview looks fine.
- [ ] The tests pass.
- [ ] The commit history is clean and meaningful.
- [ ] The pull request is opened against the `main` branch.
- [ ] The pull request is no longer marked as a draft.
- [ ] You agree to license your contribution under the [MIT license](https://github.com/spacelift-io/user-documentation/blob/main/LICENSE) to Spacelift (not required for Spacelift employees).
- You have updated the navigation files correctly:
    - [ ] No new pages have been added, or;
    - [ ] Only _nav.yaml_ has been updated because the changes only apply to SaaS, or;
    - [ ] Only _nav.self-hosted.yaml_ has been updated because the changes only apply to Self-Hosted, or;
    - [ ] Both _nav.yaml_ and _nav.self-hosted.yaml_ have been updated.

If the proposed change is ready to be merged, please request a review from `@spacelift-io/solutions-engineering`. Someone will review and merge the pull request.

_Spacelift employees should request reviews from the relevant engineers and are allowed to merge pull requests after they got at least one approval._

Thank you for your contribution! 🙇

2024-09-19 21:50 UTC, akmal-spacelift commented
https://spacelift-user-documentation-pr-634.onrender.com/integrations/cloud-providers/aws.html

2024-09-20 09:29 UTC, eminalemdar requested changes

2024-09-20 09:29 UTC, eminalemdar commented on docs/integrations/cloud-providers/aws.md
> +    If you get the error `you need to configure trust relationship section in your AWS account` when attaching a cloud integration to a stack, it may be caused by not having the [STS (Security Token
```suggestion
    If you get the error `you need to configure trust relationship section in your AWS account` when attaching a cloud integration to a stack, it may be caused by not having the [STS (Security Token Service)](https://spacelift.io/blog/aws-sts) enabled. Please make sure this service is [enabled](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html#sts-regions-activate-deactivate){: rel="nofollow"} for both the **eu-west-1** and **eu-central-1** (used for disaster recovery failover) regions in your account.
```

we add the `nofollow` for the external links in the documentation.

2024-09-20 16:24 UTC, akmal-spacelift commented on docs/integrations/cloud-providers/aws.md
> +    If you get the error `you need to configure trust relationship section in your AWS account` when attaching a cloud integration to a stack, it may be caused by not having the [STS (Security Token
cool

2024-09-23 22:14 UTC, eminalemdar approved these changes

2024-09-24 01:20 UTC, merged