Add example of multi-stack trust relationship
spacelift-io/user-documentation pull request #70
Opened 2022-09-30 16:51 UTC by adamconnelly

# Description of the change

I've added an example of how to use a `for_each` block along with the `spacelift_aws_integration_attachment_external_id` data source to generate the trust relationship for attaching a single integration to multiple stacks.

## Checklist

Please make sure that the proposed change checks all the boxes below before requesting a review:

- [ ] I have reviewed the [guidelines for contributing](https://github.com/spacelift-io/user-documentation/blob/main/CONTRIBUTING.md) to this repository.
- [ ] The preview looks fine.
- [ ] The tests pass.
- [ ] The commit history is clean and meaningful.
- [ ] The pull request is opened against the `main` branch.
- [ ] The pull request is no longer marked as a draft.
- [ ] You agree to license your contribution under the [MIT license](https://github.com/spacelift-io/user-documentation/blob/main/LICENSE) to Spacelift.

If the proposed change is ready to be merged, please request a review from `@spacelift-io/solutions-engineering`. Someone will review and merge the pull request.

Thank you for your contribution! 🙇

2022-09-30 20:04 UTC, jmfontaine requested changes
Just a minor formatting issue, otherwise it looks good to me. 👍

2022-09-30 20:04 UTC, jmfontaine commented on docs/integrations/cloud-providers/aws.md
> +```hcl
```suggestion
```terraform
```

2022-10-03 09:53 UTC, adamconnelly commented
@jmfontaine that's the problem fixed.

2022-10-03 13:53 UTC, jmfontaine approved these changes
LGTM 👍

2022-10-03 13:53 UTC, merged