Document Smart Sanitization
spacelift-io/user-documentation pull request #72
Opened 2022-10-03 21:33 UTC by jmfontaine

# Description of the change

Document Smart Sanitization

## Checklist

Please make sure that the proposed change checks all the boxes below before requesting a review:

- [ ] I have reviewed the [guidelines for contributing](https://github.com/spacelift-io/user-documentation/blob/main/CONTRIBUTING.md) to this repository.
- [ ] The preview looks fine.
- [ ] The tests pass.
- [ ] The commit history is clean and meaningful.
- [ ] The pull request is opened against the `main` branch.
- [ ] The pull request is no longer marked as a draft.
- [ ] You agree to license your contribution under the [MIT license](https://github.com/spacelift-io/user-documentation/blob/main/LICENSE) to Spacelift.

If the proposed change is ready to be merged, please request a review from `@spacelift-io/solutions-engineering`. Someone will review and merge the pull request.

Thank you for your contribution! 🙇

2022-10-04 08:45 UTC, Yantrio commented on docs/vendors/terraform/resource-sanitization.md
> +!!! warning
I'd be tempted to move this warning to the top of the section about Smart Santiziation, so that people dont get part way through then get disappointed its not in their version they use.

2022-10-04 08:51 UTC, Yantrio commented on docs/vendors/terraform/resource-sanitization.md
> +- Default Sanitization: All string values are sanitized.
```suggestion
- [Default Sanitization](#default-sanitization): All string values are sanitized.
```

maybe we should also provide a link to the Default sanitization section here?

2022-10-04 08:53 UTC, Yantrio commented
Overall it looks great, just a couple suggestions on the content.

Also would you be able to rename the image asset so its more easily identifiable please?

2022-10-04 08:53 UTC, Yantrio requested changes
.

2022-10-04 09:01 UTC, wojciech12 commented on docs/vendors/terraform/resource-sanitization.md
> +!!! warning
+1

2022-10-04 12:29 UTC, cube2222 commented on docs/vendors/terraform/resource-sanitization.md
> +                },
Right now the smart sanitization example doesn't contain **any** sanitization. I think it would be good to include a sensitive value here as well.

2022-10-04 12:30 UTC, cube2222 commented on docs/vendors/terraform/resource-sanitization.md
> +            "address": "module.instance.aws_instance.this",
address is not updated from `this` to `web`

2022-10-04 13:24 UTC, jmfontaine commented on docs/vendors/terraform/resource-sanitization.md
> +!!! warning
I was on the fence. Thanks for weighting in.

2022-10-04 13:26 UTC, jmfontaine commented on docs/vendors/terraform/resource-sanitization.md
> +            "address": "module.instance.aws_instance.this",
Good catch!

2022-10-04 13:27 UTC, jmfontaine commented on docs/vendors/terraform/resource-sanitization.md
> +                },
Yes, that is the plan. I wanted to share the PR before the end of my day to get feedback since it was complete except for the examples update.

2022-10-04 13:30 UTC, jmfontaine commented
@Yantrio 

> Also would you be able to rename the image asset so its more easily identifiable please?

They all need to be renamed at some point but you are right, I need to start somewhere.

2022-10-04 20:20 UTC, jmfontaine commented on docs/vendors/terraform/resource-sanitization.md
> +            "address": "module.instance.aws_instance.this",
I replaced the example so this is moot.

2022-10-04 20:20 UTC, jmfontaine commented on docs/vendors/terraform/resource-sanitization.md
> +- Default Sanitization: All string values are sanitized.
Fixed

2022-10-04 20:21 UTC, jmfontaine commented on docs/vendors/terraform/resource-sanitization.md
> +!!! warning
Done

2022-10-05 08:29 UTC, Yantrio approved these changes

2022-10-05 10:54 UTC, merged